### ISSUE TITLE
TODO: Add apex coordinates for points near equator

### ISSUE THREAD

**Issue by KCollins** [KCollins/conjugate-map#2]
# Description
Modified apex and quasi-dipole coordinates are two additional geomagnetic coordinate systems that would be useful for conjugate mapping.  They are well defined over the entire globe.

# TODO
- [X] Include apexpy as an optional dependency
- [x] Allow "apex" and "qdip" (or similar names) as options for the "method" kwarg
- [X] Add apex example in MWE.ipynb
- [X] Implement unit tests for apex coords
- [x] Adapt "auto" method as determined to be appropriate after testing

**Comment by KCollins** [comment]
Example code for apex coordinates, from https://github.com/aburrell/apexpy: 

```
from apexpy import Apex
import datetime as dt
atime = dt.datetime(2015, 2, 10, 18, 0, 0)
apex15 = Apex(date=2015.3)  # dt.date and dt.datetime objects also work

# Geodetic to apex, scalar input
mlat, mlon = apex15.convert(60, 15, 'geo', 'apex', height=300)
print("{:.12f}, {:.12f}".format(mlat, mlon))
# 57.477310180664, 93.590156555176

# Apex to geodetic, array input
glat, glon = apex15.convert([90, -90], 0, 'apex', 'geo', height=0)
print(["{:.12f}, {:.12f}".format(ll, glon[i]) for i,ll in enumerate(glat)])
# ['83.103820800781, -84.526657104492', '-74.388252258301, 125.736274719238']

# Geodetic to magnetic local time
mlat, mlt = apex15.convert(60, 15, 'geo', 'mlt', datetime=atime)
print("{:.12f}, {:.12f}".format(mlat, mlt))
# 56.598316192627, 19.107861709595

# can also convert magnetic longitude to mlt
mlt = apex15.mlon2mlt(120, atime)
print("{:.2f}".format(mlt))
# 20.90
```

**Comment by KCollins** [comment]
Quasidipole MWE:

```
import apexpy
import datetime as dt

# Set the location of the ISS in geodetic coordinates at a single time
stime = dt.datetime(2021, 3, 15, 15, 6)
iss_lat = 9.8
iss_lon = 142.2
iss_alt = 419.0

# Get the apex lat
apex_iss = apexpy.Apex(stime)#, refh=iss_alt)
alat, alon= apex_iss.geo2qd(iss_lat, iss_lon, iss_alt)
qlat, qlon, _ = apex_iss.qd2geo(-alat, alon, height = iss_alt)

# Get the apex height - altitude above surface where fieldline peaks
aalt = apex_iss.get_apex(alat, iss_alt)


# Convert from apex height in km to L-shell
L_iss = 1.0 + aalt / apex_iss.RE
print("apex height={:.3f} km, L={:.2f}".format(aalt, L_iss))
# apex height=428.007 km, L=1.07
```

After discussion with @aburrell, determined that: 
 - We should implement only quasidipole coordinates, not modified apex coordinates (both find the apex of the field line and trace it downward, but have different underlying assumptions; quasidipole is the appropriate system for our use case). 
 - apexpy should be an optional dependency
 - While quasidipole coordinates are the best one-size-fits-all solution, it may not be logical to make qdip the default behavior since apexpy is optional
